config/routes.rb
LennisAndRory::Application.routes.draw do
  root :to => 'Static_pages#home'
  get "venue" => "static_pages#venue"
  get "where_to_stay" => "static_pages#where_to_stay"
  get "travel" => "static_pages#travel"
  get "pics" => "static_pages#pics"
  get "local_activities" => "static_pages#local_activities"
  get "registry" => "static_pages#registry"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def venue
  end
  def where_to_stay
  end
  def travel
  end
  def local_activities
  end
  def pics
  end
  def registry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LennisAndRory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
         
          <nav>
            <ul class="nav pull-center">
				<li><%= link_to "Overview", root_path %></li>
				<li><%= link_to "Venue", venue_path %></li>
				<li><%= link_to "Where To Stay", where_to_stay_path %></li>
				<li><%= link_to "Book Flights", travel_path %></li>
				<li><%= link_to "Registry Info", registry_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

<%= yield %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37803546-1']);
  _gaq.push(['_setDomainName', 'lennisandrory.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Thanks for stopping by to get more info about our Wedding!</h2>
<!--http://www.bootstrapthemeroller.com/twitter-bootstrap-themeroller.html#@blue=#178ebf&@headingsFontWeight=bold-->
    <h5 class="text-info">We have included some resources that will hopefully make joining us on our special day as seamless as possible!</h5>
</div>


<div style="width:2500px">
<div style="padding-left:125px; float: left; width:500px">
		<img src="assets/rl_butt.jpg" class="img-rounded" alt="" style="width:450px; height:300px">
		
</div> 
<div style ="float:left; width:500px">
	<p><h4>Our Wedding is on Friday, July 26, 2013</h4></p>
	<p><h5>Here is the tentative agenda:</h5></p>
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Time</th>
				<th>What's Planned?</th>
			</tr>	
		</thead>
		<tbody>
			<tr>
				<td>4:00 PM - 4:30 PM</td>
				<td>Wedding Ceremony</td>
			</tr>
			<tr>
				<td>4:30 PM - 6:00 PM</td>
				<td>Cocktail Hour (and a half)</td>
			</tr>
			<tr>
				<td>6:00 PM - 7:30 PM</td>
				<td>Dinner</td>
			</tr>
			<tr>
				<td>7:30 PM - 10:00 PM</td>
				<td>Reception & Dancing</td>
			</tr>	
		</tbody>
	</table>
	<p><h5><strong>Please note - the terrain may be uneven so stiletto heels are strongly discouraged!</strong></h5></p>
</div>
</div>

		
	

app/views/static_pages/local_activities.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Staying for the weekend?</h2>

    <h5 class="text-info">Collectively we spent over 12 years in the San Diego area so let us give you some advice on things to do during your stay!</h5>
</div>

app/views/static_pages/pics.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Pics of friends and family</h2>

    <h5 class="text-info">Here are some of our favorite pictures of us and, in some cases, you!</h5>
</div>

app/views/static_pages/registry.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Registry</h2>

    <h5 class="text-info">Your attendance is the best gift of all, but if you would like to get us a gift, here is more info.</h5>
</div>
<div style="width:2500px">
	<div style="padding-left:125px; float: left; width:300px">
		<p><h5>We have listed some ideas at a site called RegistryLove, which allows us to list some items from various stores. We have also included options to donate to our honeymoon in Cabo.</h5></p>
		<p>
		<div class="btn btn-large btn-success">
			<a href="https://www.registrylove.com/registries/lennisandrory">Visit Registry at RegistryLove</a>
		</div>
		</p>
	</div>
		<div style ="float:left; padding-left:125px; width:500px">
			<img src="assets/lr_southie.jpg" class="img-rounded" alt="" style="width:450px; height:300px">
		</div>		
</div>	



	

app/views/static_pages/travel.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Need Help Booking Flights?</h2>

    <h5 class="text-info">Here are some details on airports in the area and some resources to help you find the best flight options from your departure cities...</h5>
</div>

<div style="width: 900px">
	<div style="padding-left:85px; float: Left; width:300px">
	<h5><p><u>Recommended Airports</u></p>
	    <p>San Diego (SAN) - 35 miles South</p>
		<p>Orange County (SNA) - 60 miles North</p>
		<p>Palomar (CLD) - 3 miles North</p></h5>
	</div>	
	<div "float: Left; width:350px">
	<script src="http://www.kayak.com/widget/?ai=kayaksample&p=&cruises=n&deals=n&vacations=n&tab=flights&l1=!&l2=SAN&doubleEncoded=on&size=300x250" style="padding-left:60px"> </script><noscript><strong>Compare hundreds of travel sites</strong> at once to find the deal that's right for you <a href='http://www.kayak.com/in?&url=/' target='_blank'>on KAYAK</a></noscript>
	</div>
</div>

app/views/static_pages/venue.html.erb
<div class="center hero-unit">
  <p><h2 class="text-info">Where is the wedding at?</h2>
	 <h5 class="text-info">
      Leo Carillo Park is an historic ranch estate in Carlsbad, CA. We chose the venue because we loved the fact that it has a laid back ambience filled with natural beauty and colors. The peacocks are pretty awesome as well!
    </h5></p>
</div>
<body>
	<div style="padding-left:30px">
		<img class="img-rounded" src="/assets/leo_entrance.png" alt="leo_entrance" style="padding:10px; width:280px; height:250px">
		<img class="img-rounded" src="/assets/leo_above.png" alt="leo_above" style="padding:10px; width:280px; height:250px">	
		<img class="img-rounded" src="/assets/leo_peacock.png" alt="leo_peacock" style="padding:10px; width:280px; height:250px">	
		<img class="img-rounded" src="/assets/leo_night.png" alt="leo_night" style="padding:10px; width:280px; height:250px">
	</div>
</body>
	<div style="padding-top: 15px; padding-left: 37%">
    <%= link_to "Learn More Here", 'http://www.carlsbadca.gov/services/departments/parksandrec/parks-facilities/parks/pages/leo-carrillo-ranch-main.aspx', 
                                class: "btn btn-large btn-success" %>
    <%= link_to "Get Directions", 'https://www.google.com/maps?q=Leo+Carrillo+Ranch+Historic+Park,+6200+Flying+Leo+Carrillo+Ln,+Carlsbad,+San+Diego,+California+92009-3042&hl=en&ll=33.118503,-117.236652&spn=0.026778,0.056863&sll=33.11113,-117.248109&sspn=0.02678,0.056863&geocode=FTZZ-QEdSxwD-Q&hnear=Leo+Carrillo+Ranch+Historic+Park,+6200+Flying+Leo+Carrillo+Ln,+Carlsbad,+California+92009-3042&t=m&z=15', 
							                                class: "btn btn-large btn-success" %>
	</div>

app/views/static_pages/where_to_stay.html.erb
<div class="center hero-unit">
    <h2 class="text-info">Where should you stay?</h2>

    <h5 class="text-info">Listed below are a few great options for accommodations in the Carlsbad area</h5>
</div>
<div class="row-fluid">
	<ul class="thumbnails">
		<li class="span4">
			<div class="thumbnail">
				<img alt="westin" style="width: 450px; height: 200px;" src="/assets/westinn.jpg">
				<div class="caption">
					<h3>West Inn - Carlsbad, CA</h3>
				<p><strong>The bride & groom are staying here. Mention "Joyce wedding party" when reserving your rooms. Rooms start at $219/nt.</strong></p>
				</div>
			<div class="btn btn-large btn-inverse">
				<a href="https://bookings.ihotelier.com/West-Inn-and-Suites/bookings.jsp?hotelId=6905&languageid=1">Reserve Now</a>
			</div>
			</div>
		</li>
		<li class='span4'>
		<div class="thumbnail">
			<img alt="la_quinta" style="width: 450px; height: 200px;" src="/assets/la_quinta.jpeg">
			<div class="caption">
				<h3>La Quinta - Carlsbad, CA</h3>
			<p><strong>The La Quinta is a more affordable option close by to both Leo Carillo and the West Inn. Rates start at $149/nt.</strong></p>
			</div>
		<div class="btn btn-large btn-inverse">
			<a href="http://www.lq.com/lq/respath/checkAvailability.do?searchCity=Carlsbad&searchState=CA&searchRadius=2&searchType=&searchOCity=&searchOState=&searchOAddress=&searchOPostal=&searchDCity=&searchDState=&searchDAddress=&searchDPostal=&corridorRadius=&excludeFromStart=&checkInMonth=07&checkInDay=25&checkInYear=2013&checkOutMonth=07&checkOutDay=26&checkOutYear=2013&palsra_IND_D=25&palsra_IND_M=07&palsra_IND_Y=2013&palsra_OTD_D=28&palsra_OTD_M=7&palsra_OTD_Y=2013&palsra_NRM=1&palsra_ROC=1&palsra_NCH=0&palsra_AMC2=&palsra_RPC1=&palsra_CCN1=&userAction=PROCESS&propId=6120&palsra_CUA1=&searchQuery=searchCity%3DCarlsbad%26searchState%3DCA%26searchType%3DGEO%26lat%3D33.10635%26lon%3D-117.31404%26availability.palsra_IND_Y%3D2013%26availability.palsra_IND_M%3D07%26availability.palsra_IND_D%3D25%26availability.palsra_OTD_Y%3D2013%26availability.palsra_OTD_M%3D07%26availability.palsra_OTD_D%3D26%26availability.palsra_NRM%3D1%26availability.palsra_ROC%3D1%26availability.palsra_NCH%3D0%26availability.palsra_AMC2%3D%26availability.palsra_RPC1%3D%26availability.palsra_CCN1%3D%26availability.palsra_CUA1%3D&resType=&confNumber=&currCode=USD">Reserve Now</a>
		</div>
		</div>
		</li>
		<li class='span4'>
		<div class="thumbnail">
			<img alt="hipmunk" style="width: 450px; height: 200px;" src="/assets/hipmunk.jpeg">
			<div class="caption">
				<h3>Other options via Hipmunk</h3>
			<p><strong>We love Hipmunk for hotel and vacation rental search. They are currently the only site that aggregates listings from Airbnb, VRBO, and HomeAway.</strong></p>
			</div>
		<div class="btn btn-large btn-inverse">
			<a href="http://www.hipmunk.com/hotels/Carlsbad-CA#!dates=Jul25,Jul28">Search Hipmunk</a>
		</div>
		</div>
		</li>
	</ul>
</div>